### ISSUE TITLE
not working with uvloop

### ISSUE THREAD

**Issue by chapagainmanoj** [sampingantech/databases-casbin-adapter#3]
I tried your solution with threading but it throws me 

```asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress```

nest_asyncio doesn't work either even if it works for asyncio loop but with some tradeoffs [according to this discussion](https://github.com/erdewit/nest_asyncio/issues/36) . So better solution could be rewriting some part of casbin itself to support async, and it seem pretty straight forward and it worked for me [with these changes](https://github.com/chapagainmanoj/pycasbin/commit/96ce4f02938cb8be40bbbb0b8edb74ba4146d89f)

**Comment by hsluoyz** [comment]
@sakti @isasetiawan

@basakest @techoner

**Comment by isasetiawan** [comment]
Hi thank you for the contribution.

 I think based on @chapagainmanoj [changes](https://github.com/chapagainmanoj/pycasbin/commit/96ce4f02938cb8be40bbbb0b8edb74ba4146d89f)  every `@to_sync()` won't be necessary and we could plug in this adapter to [asynccasbin](https://github.com/chapagainmanoj/asynccasbin), am i right?

**Comment by chapagainmanoj** [comment]
Yes, 
I have changed each io functions to async. I haven't tested all the features but only what I needed.
So you can do something like

`pip install asynccasbin`

```python

adapter = DatabasesAdapter(db_conn)
...
e = casbin.Enforcer(casbin_conf_path, None) # adapter is set to None because it can't awaited in __init__
e.set_adapter(adapter)
if not e.is_filtered():
    await e.load_policy()
```

**Comment by hsluoyz** [comment]
@chapagainmanoj plz close this issue if resolved. Also welcome to add an asynccasbin pointer to pycasbin's README
